version: "2"
services:

  frigg:
    image: frigg:latest
    command: ["-config.file=/etc/local-config.yaml"]
    volumes:
      - ./local-config.yaml:/etc/local-config.yaml
      - /tmp/frigg:/tmp/frigg
    ports:
      - "14268"      # jaeger
      - "3100:3100"  # frigg

  frigg-query:
    image: frigg-query:latest
    command: ["--grpc-storage-plugin.configuration-file=/etc/frigg-query.yaml"]
    volumes:
      - ./frigg-query.yaml:/etc/frigg-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - JAEGER_COLLECTOR_URL=http://frigg:14268
    depends_on:
      - frigg

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
    #environment:
    #  - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"