auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:
    jaeger:
      protocols:
        thrift-http:  # newer otelcol is thrift_http.  will need to change on update

ingester:
  wal:
    path: /tmp/frigg/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 10s
  traces_per_block: 1000
  max_block_duration: 30m
  max_transfer_retries: 1

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  columnar:
    boltdb:
      directory: /tmp/frigg/index
    filesystem:
      directory: /tmp/frigg/chunks
  trace:
    engine: local
    local:
      path: /tmp/frigg/traces

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0
