auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 10s
  traces_per_block: 100
  max_block_duration: 1h
  max_transfer_retries: 1
  complete_block_timeout: 2m

compactor:
  compaction:
    chunkSizeBytes: 1048576 # 1024 * 1024
    maxCompactionRange: 1h
    maxCompactionObjects: 1000000
    blockRetention: 1h
    compactedBlockRetention: 2m

storage_config:
  trace:
    maintenanceCycle: 30s
    backend: local
    wal:
      path: /tmp/tempo/wal
      bloom-filter-false-positive: .05
      index-downsample: 10
    local:
      path: /tmp/tempo/traces
    query_pool:
      max_workers: 100
      queue_depth: 10000
    cache:
      disk-path: /tmp/tempo/cache
      disk-max-mbs: 5
      disk-prune-count: 10
      disk-clean-rate: 30s   