name: Go
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.23.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install Tools
      run: make install-tools

    - name: GOPATH
      run: echo $GOPATH

    - name: Install Dependencies
      run: make vendor

    - name: Lint
      run: make lint

    - name: Test
      run: make test-with-cover

    - name: Build Frigg
      run: make frigg

    - name: Build Frigg-Query
      run: make frigg-query